package lk.ijse.gdse.util;

public enum Route {
    CASHIER_DASHBOARD, DASHBOARD, LOGIN, ORDER,CUSTOMER,ORDER_MANAGE,ADD_CUSTOMER,ADD_STOCK,ADMIN_DASHBOARD,ADD_ITEM,
    ADD_EMPLOYEE,ADD_EMPLOYEE_DETAILS,REPORTS,WELCOME,UPDATE,
}
